project_id = "ftfrktbtkxgeitgwjzis"

[functions.propose-missions]
verify_jwt = true

[functions.generate-daily-pulse]
verify_jwt = true

[functions.mentor-chat]
verify_jwt = true

[functions.share-weekly-horizon]
verify_jwt = true
